name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-check:
    name: Python Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      
      - name: Set up Python
        run: uv python install 3.11
      
      - name: Install backend dependencies
        run: |
          cd backend/store_api
          uv pip install -r requirements.txt
          cd ../checkout_service
          uv pip install -r requirements.txt
      
      - name: Check Python syntax
        run: |
          uv pip install ruff
          uv run ruff check backend/

  frontend-check:
    name: Frontend Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Type check
        run: |
          cd frontend
          npm run type-check || npx tsc --noEmit
      
      - name: Build
        run: |
          cd frontend
          npm run build