name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-check:
    name: Python Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/requirements.txt
      
      - name: Install dependencies and check Python syntax
        run: |
          # Create a virtual environment
          uv venv
          # Install all dependencies
          uv pip install -r backend/store_api/requirements.txt -r backend/checkout_service/requirements.txt ruff
          # Run ruff check
          uv run ruff check backend/

  frontend-check:
    name: Frontend Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      
      - name: Type check
        working-directory: frontend
        run: npx tsc --noEmit || true
      
      - name: Build
        working-directory: frontend
        run: npm run build