name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  python-check:
    name: Python Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/requirements.txt
      
      - name: Set up Python
        run: uv python install
      
      - name: Install Python dependencies
        run: |
          uv pip install -r backend/store_api/requirements.txt
          uv pip install -r backend/checkout_service/requirements.txt
          uv pip install ruff
      
      - name: Check Python syntax
        run: ruff check backend/ --fix=false

  frontend-check:
    name: Frontend Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      
      - name: Type check
        working-directory: frontend
        run: npx tsc --noEmit || true
      
      - name: Build
        working-directory: frontend
        run: npm run build